### ISSUE TITLE
Enable/Disable settings by language

### ISSUE THREAD

**Issue by yuki-yano** [yioneko/nvim-yati#4]
I have a setting in markdown that automatically continues the list when I make a line break.
I would like to disable yati in markdown only, because if I enable yati, that setting will not be applied.
Is it possible to add such a configuration method?

I use [lexima.vim](https://github.com/cohama/lexima.vim).

**Comment by yioneko** [comment]
Sorry, could you try the following config?
```lua
require("nvim-treesitter.configs").setup {
  yati = {
    enable = true,
    disable  = { "markdown" }
  },
}
```

**Comment by yioneko** [comment]
Documented in #8.
